model:
  DTC:
    model_params:
      default:
        ccp_alpha: 0.0
        class_weight: balanced
        criterion: gini
        max_depth: null
        max_features: sqrt
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0.0
        random_state: 0
        splitter: best
      defined:
      for_tuning:
        max_depth:
          region_1:
            start: 5
            stop: 110
            num: 11
          region_default: null
        min_samples_split:
          region_1:
            start: 0.1
            stop: 1.0
            num: 10
          region_2:
            start: 0.000001
            stop: 0.05
            num: 10
          region_default: 2
        min_samples_leaf:
          region_1:
            start: 0.1
            stop: 0.5
            num: 9
          region_2:
            start: 0.000001
            stop: 0.05
            num: 10
          region_default: 1
        max_features:
          - log2
          - sqrt
          - null
  RFC:
    model_params:
      default:
        bootstrap: True
        ccp_alpha: 0.0
        class_weight: balanced
        criterion: gini
        max_depth: null
        max_features: sqrt
        max_leaf_nodes: null
        max_samples: null
        min_impurity_decrease: 0.0
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0.0
        n_estimators: 100
        n_jobs: 4
        oob_score: False
        random_state: 0
        verbose: 0
        warm_start: False
      defined:
      for_tuning:
        bootstrap:
          - True
          - False
        min_samples_leaf:
          region_1:
            start: 0.1
            stop: 0.5
            num: 9
        min_samples_split:
          region_1:
            start: 0.1
            stop: 1.0
            num: 10
        max_features:
          - log2
          - sqrt
          - null
        n_estimators:
          region_1:
            start: 50
            stop: 2000
            num: 20
        max_depth:
          region_1:
            start: 5
            stop: 110
            num: 11
          region_default: null
  GBC:
    model_params:
      default:
        base_score: 0.5
        booster: gbtree
        colsample_bylevel: 1
        colsample_bynode: 1
        colsample_bytree: 1
        gamma: 0.0
        gpu_id: -1
        importance_type: gain
        interaction_constraints: ''
        learning_rate: 0.3
        max_delta_step: 0
        max_depth: null
        min_child_weight: 1
        missing: .NAN
        monotone_constraints: !!python/tuple []
        n_estimators: 100
        n_jobs: 4
        num_parallel_tree: 1
        random_state: 0
        reg_alpha: 0.0
        reg_lambda: 1.0
        subsample: 1
        tree_method: exact
        validate_parameters: 1
        verbosity: 0
        use_label_encoder: False
        objective: 'multi:softmax'
        eval_metric: mlogloss
      defined:
      for_tuning:
        learning_rate:
          region_1:
            start: 0.05
            stop: 0.4
            num: 15
        max_depth:
          region_1:
            start: 5
            stop: 110
            num: 11
          region_default: null
        min_child_weight:
          region_1:
            start: 1
            stop: 6
            num: 4
        gamma:
          region_1:
            start: 0.0
            stop: 0.5
            num: 5
        subsample:
          region_1:
            start: 0.5
            stop: 1.0
            num: 6
        colsample_bytree:
          region_1:
            start: 0.5
            stop: 1.0
            num: 6
        reg_alpha:
          region_1:
            start: 0.0
            stop: 100.0
            num: 20
        reg_lambda:
          region_1:
            start: 1.0
            stop: 100.0
            num: 20
        n_estimators:
          region_1:
            start: 50
            stop: 2000
            num: 20
  ANNC:
    model_params:
      default:
        units_per_layer: !!python/tuple [16, 16, 16]
        dropout: False
        dropout_rate: 0.0
        hidden_layers_activation: sigmoid
        learning_rate: 0.001
        beta_1: 0.9
        beta_2: 0.999
        epochs: 150
        batch_size: 10
        verbose: 0
      defined:
      for_tuning:
        learning_rate:
          region_1:
            start: 0.0005
            stop: 0.4
            num: 15
        epochs:
          region_1:
            start: 0.0005
            stop: 0.4
            num: 15
        units_per_layer:
          - !!python/tuple [16]
          - !!python/tuple [64]
          - !!python/tuple [128]
          - !!python/tuple [512]
          - !!python/tuple [16, 16]
          - !!python/tuple [64, 64]
          - !!python/tuple [128, 128]
          - !!python/tuple [512, 512]
          - !!python/tuple [16, 16, 16]
          - !!python/tuple [64, 64, 64]
          - !!python/tuple [128, 128, 128]
          - !!python/tuple [512, 512, 512]
        hidden_layers_activation:
          - sigmoid
          - relu