model:
  DTC:
    model_params:
      default:
        ccp_alpha: 0.0
        class_weight: balanced
        criterion: gini
        max_depth: None
        max_features: None
        max_leaf_nodes: None
        min_impurity_decrease: 0.0
        min_impurity_split: None
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0.0
        random_state: 0
        splitter: best
      defined:
      for_tuning:
  RFC:
    model_params:
      default:
        bootstrap: True
        ccp_alpha: 0.0
        class_weight: balanced
        criterion: gini
        max_depth: None
        max_features: auto
        max_leaf_nodes: None
        max_samples: None
        min_impurity_decrease: 0.0
        min_impurity_split: None
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0.0
        n_estimators: 100
        n_jobs: 4
        oob_score: False
        random_state: 0
        verbose: 0
        warm_start: True
      defined:
      for_tuning:
  GBC:
    model_params:
      default:
        ccp_alpha: 0.0
        criterion': friedman_mse
        init: None
        learning_rate: 0.1
        loss: deviance
        max_depth: 3
        max_features: None
        max_leaf_nodes: None
        min_impurity_decrease: 0.0
        min_impurity_split: None
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0.0
        n_estimators: 100
        n_iter_no_change: None
        random_state: 0
        subsample: 1.0
        tol: 0.0001
        validation_fraction: 0.1
        verbose: 0
        warm_start: False
      defined:
      for_tuning:
  ANNC:
    model_params:
      default:
        activation: relu
        alpha: 0.0001
        batch_size: auto
        beta_1: 0.9
        beta_2: 0.999
        early_stopping: False
        epsilon: 1e-08
        hidden_layer_sizes: (100,)
        learning_rate: constant
        learning_rate_init: 0.001
        max_fun: 15000
        max_iter: 200
        momentum: 0.9
        n_iter_no_change: 10
        nesterovs_momentum': True
        power_t: 0.5
        random_state: None
        shuffle: True
        solver: adam
        tol: 0.0001
        validation_fraction: 0.1
        verbose: False
        warm_start: False
      defined:
      for_tuning: