model:
  RFC:
    model_params:
      default:
        bootstrap: True
        ccp_alpha: 0.0
        class_weight: balanced
        criterion: gini
        max_depth: null
        max_features: sqrt
        max_leaf_nodes: null
        max_samples: null
        min_impurity_decrease: 0.0
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0.0
        n_estimators: 100
        n_jobs: 4
        oob_score: False
        random_state: 0
        verbose: 0
        warm_start: False
      defined:
      for_tuning:
        bootstrap:
          - True
          - False
        min_samples_leaf:
          region_1:
            start: 0.1
            stop: 0.5
            num: 9
          region_2:
            start: 0.0001
            stop: 0.05
            num: 10
          region_default: 1
        min_samples_split:
          region_1:
            start: 0.1
            stop: 1.0
            num: 10
          region_2:
            start: 0.0001
            stop: 0.05
            num: 10
          region_default: 2
        max_features:
          - log2
          - sqrt
          - null
        n_estimators:
          region_1:
            start: 50
            stop: 2000
            num: 20
        max_depth:
          region_1:
            start: 5
            stop: 110
            num: 11
          region_default: null
  ANNC:
    model_params:
      default:
        units_per_layer: !!python/tuple [512, 128, 32]
        dropout: !!python/tuple [False, True, False]
        dropout_rate: 0.3
        hidden_layers_activation: relu
        learning_rate: 0.001
        beta_1: 0.9
        beta_2: 0.999
        epochs: 500
        batch_size: 50
        verbose: 0
        shuffle: True
      defined:
      for_tuning:
        learning_rate:
          region_1:
            start: 0.0005
            stop: 0.4
            num: 15
        batch_size:
          region_1:
            start: 10
            stop: 100
            num: 10
        units_per_layer:
          - !!python/tuple [16]
          - !!python/tuple [64]
          - !!python/tuple [128]
          - !!python/tuple [512]
          - !!python/tuple [16, 16]
          - !!python/tuple [64, 64]
          - !!python/tuple [128, 128]
          - !!python/tuple [512, 512]
          - !!python/tuple [16, 16, 16]
          - !!python/tuple [64, 64, 64]
          - !!python/tuple [128, 128, 128]
          - !!python/tuple [512, 512, 512]
          - !!python/tuple [512, 128, 32]
        hidden_layers_activation:
          - sigmoid
          - relu