model:
  DTC:
    model_params:
      default:
        ccp_alpha: 0.0
        class_weight: None
        criterion: gini
        max_depth: None
        max_features: None
        max_leaf_nodes: None
        min_impurity_decrease: 0.0
        min_impurity_split: None
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0.0
        random_state: 0
        splitter: best
      defined:
      for_tuning:
  RFC:
    model_params:
      default:
        bootstrap: True
        ccp_alpha: 0.0
        class_weight: None
        criterion: gini
        max_depth: None
        max_features: auto
        max_leaf_nodes: None
        max_samples: None
        min_impurity_decrease: 0.0
        min_impurity_split: None
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0.0
        n_estimators: 100
        n_jobs: 4
        oob_score: False
        random_state: 0
        verbose: 0
        warm_start: False
      defined:
      for_tuning:
  GBC:
    model_params:
      default:
        ccp_alpha: 0.0
        criterion': friedman_mse
        init: None
        learning_rate: 0.1
        loss: deviance
        max_depth: 3
        max_features: None
        max_leaf_nodes: None
        min_impurity_decrease: 0.0
        min_impurity_split: None
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0.0
        n_estimators: 100
        n_iter_no_change: None
        random_state: 0
        subsample: 1.0
        tol: 0.0001
        validation_fraction: 0.1
        verbose: 0
        warm_start: False
      defined:
      for_tuning:
  ANNC:
    model_params:
      default:
      defined:
      for_tuning: